---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.1.5
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
  interval: 1m0s
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  values:
    clusterName: SHOULD-BE-PATCHED
    autoDiscoverAwsRegion: true
    autoDiscoverAwsVpcID: true
    image:
      repository: <account_id>.ecr.eu-west-1.amazonaws.com/amazon/aws-load-balancer-controller
      tag: v2.1.3
