---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
  interval: 1m0s
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  values:
    image:
      repository: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver  # Modify public image to private
    controller:
      serviceAccount:
        name: ebs-csi-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/ebs-csi-driver-service-account-role
