---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://external-secrets.github.io/kubernetes-external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-external-secrets
      sourceRef:
        kind: HelmRepository
        name: kubernetes-external-secrets
      version: 8.3.0
  interval: 1m0s
  targetNamespace: kube-system
  values:
    fullnameOverride: external-secrets
    replicaCount: 1
    image:
      tag: 8.3.0
    env:
      AWS_REGION: eu-west-1
    serviceAccount:
      create: true
      name: external-secrets-oidc
      securityContext:
        fsGroup: 65534
