apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-application-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-application
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50