apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: your-namespace
  labels:
    size: small
spec:
  hard:
    pods: "5"  # Maximum allowed number of pods
    services: "2"  # Maximum allowed number of services
    configmaps: "5"
    persistentvolumeclaims: "2"
    replicationcontrollers: "5"
    secrets: "5"
    service.loadbalancers: "2"
    service.nodeports: "3"
    count/deployments.apps: "4"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
    limits.cpu: "4"
    
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
  namespace: your-namespace
  labels:
    size: small
spec:
  limits:
    - type: "Container"
      default:
        memory: "384Mi"
        CPU: "200m"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 50m
        memory: 32Mi
