apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: your-namespace
  labels:
    size: small
spec:
  hard:
    pods: "5"  # Maximum allowed number of pods
    services: "2"  # Maximum allowed number of services
    persistentvolumeclaims: "2"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
  namespace: your-namespace
  labels:
    size: small
spec:
  limits:
    - type: "Container"
      default:
        memory: "384Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"