apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.caConfigMap.name }}
  namespace: {{ .Values.webhookService.namespace }}
data:
  ca-cert.pem: |
    {{ .Values.certificates.caCert | indent 4 }}
