apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecret.name }}
  namespace: {{ .Values.webhookService.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.certificates.webhookCert | b64enc | indent 4 }}
  tls.key: |
    {{ .Values.certificates.webhookKey | b64enc | indent 4 }}
