# templates/validating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespace.webhook.example.com
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: namespace.webhook.create.com
    clientConfig:
      caBundle: {{ .Values.certificates.caCert | b64enc | quote }}
      service:
        name: {{ .Values.webhookService.name }}
        namespace: {{ .Values.webhookService.namespace }}
        path: /webhook
        port: {{ .Values.webhookService.port }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    failurePolicy: Ignore
    sideEffects: None
  - name: namespace.webhook.delete.com
    clientConfig:
      service:
        name: {{ .Values.webhookService.name }}
        namespace: {{ .Values.webhookService.namespace }}
        path: /delete
        port: {{ .Values.webhookService.port }}
      caBundle: {{ .Values.certificates.caCert | b64enc | quote }}
    rules:
      - operations: ["DELETE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    failurePolicy: Ignore
    sideEffects: None
