apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-agent-system-probe-config
  namespace: default
data:
  system-probe.yaml: |
    system_probe_config:
      enabled: true
      debug_port: 0
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
      enable_conntrack: true
      bpf_debug: false